@startuml

hide footbox

participant "Requester" as Reader
participant "Responder" as Repo

activate Reader
activate Repo
Reader->Repo: Find Multimedia DiagnosticReports
Repo-->Reader: Return DiagnosicReports Bundle
deactivate Repo
deactivate Reader

@enduml