@startuml

actor "Radiologist" as Rad

participant "Report Creator" as RCreator
participant "Report Repository" as Repo
participant "Rendered Report Reader\n(EMR)" as EMR

participant "Image Manager/\nImage Archive" as Archive

actor Clinician as Clinician

Rad->>RCreator: //Finish report with//\n//multimedia references//
RCreator->RCreator: //Create multimedia report//\n//including the rendered version//\n//of report//\n//(Report X)//
RCreator->RCreator: //Embed links to rendered//\n//versions of referenced images//

RCreator->Repo: Store Multimedia Report [RAD-141]\n(Report X)

Clinician->>EMR: //Select accession X//

EMR->Repo: Find Multimedia Report [RAD-143]
Repo-->EMR:(Report X)

alt Report X contains embedded rendered report
EMR->>EMR: //Extract and decode//\n//embedded report//
else Report X contains URL for rendered report
EMR->Repo: Retrieve Rendered Multimedia Report [RAD-144]
Repo-->EMR: (Rendered Report X)
end

EMR->EMR: Display Multimedia Report [RAD-142]
Clinician->>EMR: //Click on hyperlinked image reference//

EMR->Archive: WADO-RS Retrieve [RAD-107]\nRetrieve rendered images
Archive-->EMR: (Rendered images)
EMR->EMR: Display Images [RAD-145]

@enduml