@startuml

actor Clinician as Clinician

participant "Report Reader\n(EMR)" as Reader
participant "Report Repository" as Repo

participant "Image Manager/\nImage Archive" as Archive

Clinician->>Reader: //Select report entry//

Reader->Repo: Find Multimedia Report [RAD-143]
Repo-->Reader: Returned multimedia report
Reader->Reader: Display Multimedia Report [RAD-142]
note over Reader
Show report, including hyperlinked references to measurements and/or images.
end note

Clinician->>Reader: //Click on hyperlinked measurements//

loop Retrieve DICOM objects and/or rendered images with / without additional presentation, window levelling
Reader->Archive: Retrieve images in series\nWADO-RS Retrieve [RAD-107]
Reader->Reader: Display Images [RAD-145]

Clinician->>Reader: //Interact with images and/or series//\n//such as scrolling or window levelling//
end loop

@enduml