@startuml

title "Use Case 2: Present Multimedia Report in EMR with Native IMR Report Reader\n(Direct support of Interactive Multimedia Report)"

actor Clinician as Clinician

box Grouped Actors
participant "Report Reader\n(EMR)" as EMR
participant "Report Repository" as Repo
end box

participant "Imaging Document Source" as Archive

Clinician->>EMR: //Request multimedia report//
group IMR Interactive Viewing of Multimedia Content in Report
EMR->>Repo: //Retrieve multimedia report//
EMR->EMR: [RAD-Y2] Display Multimedia Report
note over EMR
Present report, including multimedia contents
such as measurements and image references.
end note

Clinician->>EMR: //Click on image references//
EMR->Archive: Retrieve images in series\n[RAD-107] WADO-RS Retrieve
EMR->>EMR: //Display series//

Clinician->>EMR: //Interact with images and/or series//
end

@enduml