@startuml

actor Clinician as Clinician

box Grouped Actors
participant "Rendered Report Reader\n(EMR)" as EMR
participant "Report Repository" as Repo
end box

participant "Imaging Document Source" as Archive

Clinician->>EMR: //Request multimedia report//
group IMR Interactive Viewing of Multimedia Content in Report
EMR->Repo: [RAD-Y3] Find Multimedia Report
EMR->EMR: [RAD-Y2] Display Multimedia Report
note over EMR
Extract the rendered report from the retrieved multimedia report.
end note

opt If report is referenced by a URL
EMR->Repo: [RAD-Y4] Retrieve Rendered Multimedia Report
Repo-->EMR: Return rendered multimedia report
end

Clinician->>EMR: //Click on hyperlinked measurements//

EMR->Archive: Retrieve rendered images in series\n[RAD-107] WADO-RS Retrieve
EMR->>EMR: //Display images with measurements shown in ROI//

Clinician->>EMR: //Interact with images and/or series//\n//such as scrolling or window levelling//

end

@enduml