@startuml

actor Clinician as Clinician

box Grouped Actors
participant "EMR" as EMR
participant "Image Display\nInvoker" as Invoker
end box

box Grouped Actors
participant "Image Display" as Display
participant "Report Reader" as Reader
end box

participant "Report Repository" as Repo
participant "Image Manager/\nImage Archive" as Archive

Clinician->>EMR: //Navigate patient's study//
EMR->>Invoker: //Navigate study//

Invoker->Display: Invoke Image Display [RAD-106]
Display->>Archive: //Retrieve study//
Archive-->>Display: //Return study//
Display->>Display: //Display study//
Display->>Reader: //Show associated multimedia report//

group IMR Interactive Viewing of Multimedia Content in Report
Reader->Repo: Find Multimedia Report [RAD-143]
Repo-->Reader: Return multimedia report
Reader->Reader: Display Multimedia Report [RAD-142]

note over Reader
Present report, including hyperlinked references to measurements and/or images.
end note

Clinician->>Reader: Click on image references in Report
Reader->>Display: //View series//\n//(internal communication)//
Display->>Archive: //Retrieve series//
Display->Display: Display Images [RAD-145]

Clinician->>Display: //Interact with image and/or series//
end

@enduml