@startuml

actor Radiologist as Radiologist

participant "Report Creator" as RCreator

box Grouped Actors
participant "Image Display" as Display
participant "Report Reader" as Reader
end box

participant "Report Repository" as Repo
participant "Image Manager/\nImage Archive" as Archive

Radiologist->>RCreator: //Begin Dictation//
Radiologist->>Display: //View current study with prior studies and//\n//associated multimedia reports//
Display->>Archive: //Retrieve current and prior studies//
Archive-->>Display: //Return studies//
Display->>Display: //Display studies//

group IMR Interactive Viewing of Multimedia Content in Report for Prior Studies
Display->>Reader: //Select report entry//
Reader->Repo: Find Multimedia Report\nfor prior studies [RAD-Y3]
Repo-->Reader: Returned multimedia report
Reader->Reader: Display Multimedia Report [RAD-Y2]

note over Reader
Present report, including hyperlinked references to measurements and/or images.
end note

Radiologist->>Reader: //Click on image references in Report//
Reader->>Display: //Launch images from prior study//\n//(internal communication)//
Display->>Display: //Display images//
note over Display
Since the Image Display is the more feature-rich radiology workstation,
the Image Display has more capability to display the referenced images
in the multimedia report than RAD-Y5.
end note

loop Retrieve images, presentation states, window levelling
alt Using WADO-RS Retrieve
Display->Archive: WADO-RS Retrieve [RAD-107]
else Using DIMSE Retrieve
Display->Archive: Retrieve Images [RAD-16], Retrieve Presentation States [RAD-17],\nRetrieve Key Image Notes [RAD-31], Retrieve Evidence Documents [RAD-45]
end

Radiologist->>Display: //Interact with images and/or series//\n//such as scrolling, re-measure//
end loop

end

Radiologist->>RCreator: //End Dictation//
RCreator->>RCreator: //Generate new multimedia report for current study//\n//following Use Case 1//


@enduml